openapi: '3.0.2'
info:
  title: Event Service
  version: '1.0'
  description: Provides a set of API operations that can be performed on a user like updating and retrieving Event Details.
  license:
    name: Proximety
    url: www.proximety.io
servers:
  - url: https://app-dev.proximety.io/api
  - url: https://app-staging.proximety.io/api
  - url: https://app-patch.proximety.io/api
  - url: https://app.proximety.io/api
tags:
- name: EventsResource
paths:
  /events/_query:
    post: 
      tags:
        - Events
      summary: Returns Details of all Events of the Mall.
      operationId: getAdminAddedEvents
      requestBody:
       description: The Event Details to be Updated. 
       content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventSearchRequest'
       required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventsListResponse'
        "400":
          description: Bad request
        "403":
          description: Unauthorized access
  /events:         
    post: 
      tags:
        - Events
      summary: Create event
      description: Creates a new event schedule for the shopping mall.
      operationId: createEvent
      requestBody:
        description: The details of the event to be created.
        content:
         application/form-data:
             schema:
                type: object
                properties:
                 event:
                  type: object
                  $ref: '#/components/schemas/EventRequestDTO'
                 banner:
                  format: binary
                  example: Expects an Image for event banner
                 poster:
                  format: binary
                  example: Expects an Image for event poster
                 wide-banner:
                  format: binary
                  example: Expects an Image for event wide banner
      responses:
        "201":
          description: Event Created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponseDTO'
        "400":
          description: Bad request
        "403":
          description: Unauthorized access
  /events/{eventId}/orders:
    post: 
      tags: 
        - Event Tickets
      summary: Create a ticket order which will block the seats for 5 minutes
      operationId: CreateEventTicketOrder
      parameters:
        - name: eventId
          in: path
          description: The internal system identifier for the event for which the order is to be created.
          required: true
          schema:
            type: string
      requestBody:
       description: The Order Details 
       content:
            application/form-data:
             schema:
                type: object
                properties:
                 event:
                  type: object
                  $ref: '#/components/schemas/EventOrderRequest'
       required: true
      responses:
        "201":
            description: Details of the created order
            content: 
              application/json:
                schema:
                  $ref: '#/components/schemas/EventOrderResponse'
        "400":
          description: Bad request
        "403":
          description: Forbidden
  /event-orders/{orderId}/payment:
    post: 
      tags: 
        - Event Tickets
      summary: Initate payment for the ticket order
      operationId: InitiateTicketPayment
      parameters:
        - name: orderId
          in: path
          description: The internal system identifier for the order for which payment is to be initiated.
          required: true
          schema:
            type: string
      responses:
        "201":
            description: Details of the created order
            content: 
              application/json:
                schema:
                  $ref: '#/components/schemas/InitiatePaymentResponse'
        "400":
          description: Bad request
        "403":
          description: Forbidden
  /events/{eventId}:
    get: 
      tags:
        - Events
      summary: Get Event Details that's created.
      operationId: getEventDetails
      parameters:
        - name: eventId
          in: path
          description: The internal system identifier for the event whose details are to be fetched.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Event Details Successfully Retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponseDTO'
        "400":
          description: Bad request
        "403":
          description: Forbidden
    put: 
      tags:
        - Events
      summary: Update Created Event Details.
      operationId: updateEvent
      
      parameters: 
        - name: eventId
          in: path
          description: The internal system identifier for the event whose details are to be updated.
          required: true
          schema:
            type: string    
      requestBody:
       description: The Event Details to be Updated. 
       content:
            application/form-data:
             schema:
                type: object
                properties:
                 event:
                  type: object
                  $ref: '#/components/schemas/EventRequestDTO'
                 banner:
                  format: binary
                  example: Expects an Image for event banner
                 poster:
                  format: binary
                  example: Expects an Image for event poster
       required: true
      responses:
        "204":
          description: Event Details Successfully Updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponseDTO'
        "400":
          description: Bad request
        "403":
          description: Forbidden
  
    delete: 
      tags:
        - Events
      summary: Delete a particluar Event.
      operationId: deleteEvent
      parameters:
        - name: eventId
          in: path
          description: Used as an identifier for the mall whose events are fetched.
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Delete Event.
        "400":
          description: Bad request
        "403":
          description: Forbidden
components:
  schemas:
    InitiatePaymentResponse: 
      type: object
      properties:
        transactionId: 
          type: string
          description: The internal system identifier for the transaction 
        encryptedData: 
          type: string
          description: The encrypted request to be used for initiating transaction with CCAvenue 
        accessCode: 
          type: string
          description: The CCAvenue Access Code 
        merchantId: 
          type: string
          description: The CCAvenue Merchant Code
        successCallbackUrl: 
          type: string
        failureCallbackUrl: 
          type: string
    EventOrderRequest: 
      type: object
      properties:
        tickets: 
          type: array
          items:
            $ref: '#/components/schemas/TicketOrderRequest'
    EventOrderResponse: 
      type: object
      properties:
        orderId: 
          type: string
          description: The nternal system identifier for the order created.
          example: 831001
        ticketingDetails:
          type: array
          description: The details of the tickets being booked.
          items: 
            $ref: '#/components/schemas/TicketOrderDetail'
        event: 
          $ref: '#/components/schemas/EventSummary'
        billingDetails: 
          type: object
          description: The billing details for the order being placed.
          properties:
            totalAmount: 
              type: number
              example: 1100
            breakup: 
              type: array
              description: The brakup of total amount. 
              items:
                type: object
                properties:
                  feeType:
                    type: string
                    description: The name of the brakup type.\
                    example: Convenience fee
                  amount: 
                    type: number
                    example: 700
    TicketOrderDetail: 
      type: object
      properties:
        ticketTypeId:
          type: string
        ticketTypeName: 
          type: string
          description: The ticket type name.
        quantity: 
          type: number
          example: 10
    TicketOrderRequest:
      type: object
      properties:
        ticketTypeId:
          type: string
          description: The internal identifier for the type of ticket selected.
        quantity: 
          type: number
          description: The number of tickets to be booked for the selected type.
          example: 5    
    EventsListResponse:
      type: object
      description: The event search response that contains the list of events matching the search criteria.
      properties:
        countInCurrentPage: 
          type: integer
          description: The count of events returned in the search response.
          example: 10
        totalCount: 
          type: integer
          description: The total number of events that match the specified search criteria.
          example: 100
        eventsList:
          type: array
          description: The embedded search results
          items:
                $ref: '#/components/schemas/EventResponseDTO'
    EventSummary: 
      type: object
      properties:
       eventId:
          type: string
          description: The internal system identifier for the Event.
          example: 00E7A620-4E8A-4F40-85DC-A1A62DF6D4EA
       mallId:
          type: string
          description: The internal system identifier for the Mall.
          example: 00E7A620-4E8A-4F40-85DC-A1A62DF6D4EA
       name:
          type: string
          description: Name of the Event.
          example: Womens' day celebration
       status:
          type: string
          description: Represents the status of the Event whether its running,gone past or its upcoming.
          example: UPCOMING
          enum:
            - UPCOMING
            - NOW_RUNNING
            - PAST
       startDate:
          type: string
          description: Filter Events based on its Start Date
          example: 2023-12-13T23:22:53.000000
       endDate:
          type: string
          description: Filter Events based on its End Date
          example: 2023-12-13T23:22:53.000000
       poster:
          type: string
          format: uri
          example: https://dev.proximety.io/images/21423.jpg
       banner:
          type: string
          format: uri
          example: https://dev.proximety.io/images/21423.jpg
       wideBanner:
          type: string
          format: uri
          example: https://dev.proximety.io/images/21423.jpg
       description:
          type: string
          description: Gives general Info about the Event.
          example: Womens' day is celebrated 8th March every year.
       eventType:
          type: string
          example: ALL_DAY
          enum:
              - ALL_DAY
              - MULTI_DAY
              - SCHEDULED
    EventResponseDTO:
      type: object
      properties:
       eventId:
          type: string
          description: The internal system identifier for the Event.
          example: 00E7A620-4E8A-4F40-85DC-A1A62DF6D4EA
       mallId:
          type: string
          description: The internal system identifier for the Mall.
          example: 00E7A620-4E8A-4F40-85DC-A1A62DF6D4EA
       name:
          type: string
          description: Name of the Event.
          example: Womens' day celebration
       status:
          type: string
          description: Represents the status of the Event whether its running,gone past or its upcoming.
          example: UPCOMING
          enum:
            - UPCOMING
            - NOW_RUNNING
            - PAST
       startDate:
          type: string
          description: Filter Events based on its Start Date
          example: 2023-12-13T23:22:53.000000
       endDate:
          type: string
          description: Filter Events based on its End Date
          example: 2023-12-13T23:22:53.000000
       poster:
          type: string
          format: uri
          example: https://dev.proximety.io/images/21423.jpg
       banner:
          type: string
          format: uri
          example: https://dev.proximety.io/images/21423.jpg
       wideBanner:
          type: string
          format: uri
          example: https://dev.proximety.io/images/21423.jpg
       description:
          type: string
          description: Gives general Info about the Event.
          example: Womens' day is celebrated 8th March every year.
       eventType:
          type: string
          example: ALL_DAY,MULTI_DAY,SCHEDULED
          enum:
              - ALL_DAY
              - MULTI_DAY
              - SCHEDULED
       artists: 
        type: array
        items:
          $ref: "#/components/schemas/EventArtist"
       faqs:
        type: array
        items: 
          type: string
       termsAndConditions:
        type: array
        items: 
          type: string
       ticketingEnabled:
          type: boolean
          description: Indicates whether ticketing is enabled for the event
          example: true
       ticketingStartTime:
        type: string
        example: 2023-12-13T23:22:53.000000
       ticketingEndTime:
        type: string
        example: 2023-12-13T23:22:53.000000
       ticketingActive: 
          type: boolean
       ticketingDetails:
        type: object
        properties: 
          ticketStartPrice: 
            type: number
            example: 90
            description: The starting price of tickets for the event.
          availableTickets:
            type: array
            items:
                $ref: '#/components/schemas/TicketDetailsResponse'
    TicketDetailsResponse:
      type: object
      properties:
        ticketTypeId: 
          type: string
        name:
          type: string
          example: VIP Pass
        price:
          type: number
          example: 100
        ticketsAvailable:
          type: number
          example: 50
        ticketsSold:
          type: number
          example: 50
        status: 
          type: string
          enum: 
            - AVAILABLE
            - FILLING_FAST
            - SOLD_OUT
        additionalDetails:
          type: array
          items:
            type: string
    EventRequestDTO:
      type: object
      properties:
       name:
          type: string
          description: Name of the Event.
          example: Womens' day celebration
       startDate:
          type: string
          description: Filter Events based on its Start Date
          example: 2023-12-13T23:22:53.000000
       endDate:
          type: string
          description: Filter Events based on its End Date
          example: 2023-12-13T23:22:53.000000
       description:
          type: string
          description: Gives general Info about the Event.
          example: Womens' day is celebrated 8th March every year.    
       eventType:
          type: string
          example: ALL_DAY,MULTI_DAY,SCHEDULED
          enum:
              - ALL_DAY
              - MULTI_DAY
              - SCHEDULED
       artists: 
        type: array
        items:
          $ref: "#/components/schemas/EventArtist"
       faqs:
        type: array
        items: 
          type: string
       termsAndConditions:
        type: array
        items: 
          type: string
       ticketingEnabled:
          type: boolean
          description: Indicates whether ticketing is enabled for the event
          example: true
       ticketingStartTime:
        type: string
        example: 2023-12-13T23:22:53.000000
       ticketingEndTime:
        type: string
        example: 2023-12-13T23:22:53.000000
       ticketingDetails:
        type: object
        properties: 
          availableTickets:
            type: array
            items:
                $ref: '#/components/schemas/TicketDetails'
    EventArtist: 
      type: object
      properties:
        artistName: 
          type: string
        imageUrl: 
          type: string
    TicketDetails:
      type: object
      properties:
        name:
          type: string
          example: VIP Pass
        price:
          type: number
          example: 100
        ticketsAvailable:
          type: number
          example: 50
        additionalDetails:
          type: array
          items:
            type: string
    EventSearchRequest:  
      type: object
      properties:   
        name:
         type: string
         description: Filter Events based on its Start Date
         example: Event 1
        eventStatuses:
          type: array
          description: A list of event status. Only events having a status specified in the list will be retrieved.
          items:
            type: string
            example: RUNNING,GONEPAST,UPCOMING
            enum:
              - GONEPAST
              - RUNNING
              - UPCOMING
        startDate:
          type: string
          description: Filter Events based on its Start Date
          example: 2023-12-13T23:22:53.000000
        endDate:
          type: string
          description: Filter Events based on its End Date
          example: 2023-12-13T23:22:53.000000
        page:
          type: integer
          description: The search offset for doing paginated search.
          example: 20
          default: 0
        size: 
          type: integer
          description: The page size for doing paginated search
          example: 10
          default: 10
