openapi: '3.0.2'
info:
  title: Movie Booking Service
  version: '1.0'
  description: Provides a set of API operations that can be used for viewing movie details and for booking movie tickets.
  license:
    name: Proximety
    url: www.proximety.io
servers:
  - url: https://dev.proximety.io/api
  - url: https://staging.proximety.io/api
  - url: https://www.proximety.io/api
tags:
- name: Movie
paths:
  /movies:
    get: 
      tags:
        - Movie
      summary: List movies
      description: API to get the list of all movies.
      operationId: getMovies
      parameters:
        - name: Authorization
          in: header
          description: The authentication bearer token.
          required: true
          example: Bearer asd.js2jd9a.gC6paXtNOg0OZL4-adsd-asd
          schema:
            type: string
        - name: mallId
          in: query
          description: The internal system identifier for the mall.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieSummary'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GlobalException"
              example: 
                {
                  "status": 403,
                  "type": "BAD_REQUEST",
                  "title": "Mall ID not specified",
                  "detail": "The mall id of th mall for which the movie listing needs to be retrieved has not been specified. Please specify a valid mall id and try again.",
                  "tags":[]
                }
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GlobalException"
              example: 
                {
                  "status": 403,
                  "type": "NOT_FOUND",
                  "title": "Mall not found",
                  "detail": "No shopping mall found for the specified mall id.",
                  "tags":[]
                }
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GlobalException"
              example: 
                {
                  "status": 403,
                  "type": "FORBIDDEN",
                  "title": "Token expired.",
                  "detail": "The specified access token has expired. Please try again with an active access token.",
                  "tags":[]
                }
  /movies/{movieId}:
    get: 
      tags:
        - Movie
      summary: Movie details
      description: Retrieves the details of a movie.
      operationId: getMovies
      parameters:
        - name: Authorization
          in: header
          description: The authentication bearer token.
          required: true
          example: Bearer asd.js2jd9a.gC6paXtNOg0OZL4-adsd-asd
          schema:
            type: string
        - name: movieId
          in: path
          description: The internal system identifier for the movie.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieDetails'
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GlobalException"
              example: 
                {
                  "status": 403,
                  "type": "NOT_FOUND",
                  "title": "Movie not found",
                  "detail": "The requested movie could not be found. Please try again with an available movie id.",
                  "tags":[]
                }
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GlobalException"
              example: 
                {
                  "status": 403,
                  "type": "FORBIDDEN",
                  "title": "Token expired.",
                  "detail": "The specified access token has expired. Please try again with an active access token.",
                  "tags":[]
                }
  /movies/{movieId}/schedule:
    get:
      tags:
        - Movie
      summary: Movie schedule
      description: Retrieves the schedule of a movie.
      operationId: getSchedule
      parameters:
        - name: Authorization
          in: header
          description: The authentication bearer token.
          required: true
          example: Bearer asd.js2jd9a.gC6paXtNOg0OZL4-adsd-asd
          schema:
            type: string
        - name: movieId
          in: path
          description: The internal system identifier for the movie.
          required: true
          schema:
            type: string
        - name: mallHandle
          in: query
          description: The internal system identifier for the mall.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Schedule'
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GlobalException"
              example: 
                {
                  "status": 403,
                  "type": "NOT_FOUND",
                  "title": "Movie not found",
                  "detail": "The requested movie could not be found. Please try again with an available movie id.",
                  "tags":[]
                }
        "403":
          description: Forbidden   
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GlobalException"
              example: 
                {
                  "status": 403,
                  "type": "FORBIDDEN",
                  "title": "Token expired.",
                  "detail": "The specified access token has expired. Please try again with an active access token.",
                  "tags":[]
                }
components:
  schemas:
    GlobalException:
      type: object
      description: An exception thrown by the system.
      properties:
        status:
          type: integer
          description: The status code for the error.
          example: 401
        type:
          type: string
          description: The type name for the error being thrown.
          example: UNAUTHORIZED
        title:
          type: string
          description: The error title.
          example: Token expired.
        detail:
          type: string
          description: The details of the error being thrown.
          example: The access token has expired for the user. Please generate a new token and try again.
        tags:
          type: array
          description: The varios tags associated with the error that provides additional information about the error.
          items: 
            type: string
            example: ACCESS_TOKEN_INVALID 
    MovieSummary:
      type: object
      required:
        - movieName
        - language
        - releaseDate
      properties:
        movieId:
          type: integer
          description: The internal system identifier for a movie.
          example: 123
        movieName:
          type: string
          description: Name of the movie.
          example: Kaduva
        language:
          type: string
          description: Language of the movie.
          example: malayalam
        genre:
          type: array
          items:
            $ref: '#/components/schemas/Genre'
          description: Genre of the movie.  
        releaseDate:
          type: string
          pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
          example: "2022-05-17"
        bookingOpen:
          type: boolean
          description: To indicate if booking is open for the movie.
        3D:
          type: boolean
          description: To indicate if it is a 3d movie.
        posterUrl:
          type: string
          format: uri
          description: url of the poster
          example: https://dev.proximety.io/api/movies/eahdjk14129102==
        trailerUrl:
          type: array
          $ref: '#/components/schemas/Trailer'
    MovieDetails:
      type: object
      required:
        - movieName
      properties:
        movieId:
          type: integer
          description: The internal system identifier for a movie.
          example: 123
        movieName:
          type: string
          description: Name of the movie.
          example: Kaduva
        language:
          type: string
          description: Language of the movie.
          example: malayalam
        genre:
          type: array
          description: Genre of the movie.
          items:
            $ref: '#/components/schemas/Genre'
        releaseDate:
          type: string
          pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
          example: "2022-05-17"
        bookingOpen:
          type: boolean
          description: To indicate if booking is open for the movie.
        3D:
          type: boolean
          description: To indicate if it is a 3d movie.
        posterUrl:
          type: string
          format: uri
          description: url of the poster
          example: https://dev.proximety.io/api/movies/eahdjk14129102==
        trailers:
          type: array
          items:
            $ref: '#/components/schemas/Trailer'
        duration:
          type: integer
          description: Duration of the movie in minutes.
          example: 150
        overview:
          type: string
          description: Overview of the movie
        certificate:
          type: string
          description: Certificate of the movie
          enum:
            - U
            - A
            - U/A
        director:
          type: string
          description: Name of the director
        writer:
          type: string
          description: Name of the writer
        cast:
          type: array
          $ref: '#/components/schemas/Cast'
    Schedule:
      type: object
      required:
        - scheduleId
        - movieId
      properties:
        scheduleId:
          type: integer
          description: The internal system identifier for the schedule.
          example: 422
        movieId:
          type: integer
          description: The internal system identifier for the movie.
          example: 123
        showDate:
          type: string
          pattern: /([0-9]{4})-(?:[0-9]{2})-([0-9]{2})/
          example: "2022-05-17"
        startTime:
          type: string
          description: Start time of the show
          example: 5.30 pm
        saleStatus:
          type: string
          enum: 
            - SOLDOUT
            - AVAILABLE
    Cast: 
      type: object
      properties:
        originalName: 
          type: string
          description: Name of the actor/actress
        character:
          type: string
          description: Name of the character in the movie
        profilePath:
          type: string
          format: uri
          description: url of the path in which cast image is stored
    Trailer:
      type: object
      properties:
        key:
          type: string
          description: Unique identifier for the trailer video
          example: 6JnN1DmbqoU
        site:
          type: string
          description: Name of the website in which the video is available
          example: YouTube
    Genre:
      type: object
      properties:
        name:
          type: string
          example: Action

          
