openapi: '3.0.2'
info:
  title: Shopping mall service
  version: '1.0'
  license:
    name: Proximety
    url: www.proximety.io
servers:
  - url: https://app-dev.proximety.io/api
  - url: https://app-staging.proximety.io/api
  - url: https://app-patch.proximety.io/api
  - url: https://app.proximety.io/api
  
# - name: User
# - name: Issue Ticket
paths:
  /shopping-malls/auth/login:
    post:
      tags:
        - Authentication
      summary: Login admin user
      description: Authenticates and logs in an admin user for a shopping mall.
      operationId: login   
      requestBody:
        description: The details for logging in a user into the admin platform.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        203:
          description: Created
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/LoginResponse'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/GlobalException'
              example: 
                {
                  "status": 403,
                  "type": "BAD_REQUEST",
                  "title": "Email / Password incorrect. ",
                  "detail": "The specified Email / Password is incorrect. Please specify a valid Email / Password and try again.",
                  "tags":[]
                }
  # /shopping-malls/auth/logout:
  #   post:
  #     tags:
  #       - Authentication
  #     summary: Log out admin user
  #     description: Logs out an admin user from the admin platform.
  #     operationId: logout   
  #     parameters:
  #       - name: Authorization
  #         in: header
  #         description: The authentication bearer token.
  #         required: true
  #         example: Bearer asd.js2jd9a.gC6paXtNOg0OZL4-adsd-asd
  #         schema:
  #           type: string
  #     requestBody:
  #       description: The details for logging out a user from the admin platform.
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             $ref: '#/components/schemas/LogoutRequest'
  #     responses:
  #       203:
  #         description: OK
  #         content:
  #           application/json:
  #             schema:
  #                 $ref: '#/components/schemas/LogoutResponse'
  #       400:
  #         description: Bad request
  #         content:
  #           application/json:
  #             schema:
  #                 $ref: '#/components/schemas/GlobalException'
  #             example: 
  #               {
  #                 "status": 403,
  #                 "type": "BAD_REQUEST",
  #                 "title": "User not found",
  #                 "detail": "The specified user cannot be found.",
  #                 "tags":[]
  #               }
  /shopping-malls:
    get: 
      tags:
        - Shopping mall
      summary: Search malls
      description: Rethrieves the list of malls tied to the proximety platform.
      operationId: getMalls
      parameters:
        - name: Authorization
          in: header
          description: The authentication bearer token.
          required: true
          example: Bearer asd.js2jd9a.gC6paXtNOg0OZL4-adsd-asd
          schema:
            type: string
        - name: areaCode
          in: query
          required: false 
          example: KZD
          schema:
           type: string
      responses:
        203:
          description: OK
          content:
            application/json:
              schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/ShoppingMallDetails'
  /parking-lots:
    get: 
      tags:
        - Parking
      summary: Get parking slots
      description: Retrieves the details of parking slots for the specified shopping mall.
      parameters:
        - name: mallId
          in: path
          description: The intenal system identifier for the shopping mall whose parking slot details are to be fetched.
          required: true
          example: asd.js2jd9a.gC6paXtNOg0OZL4-adsd-asd
          schema: 
            type: string
      responses:
        200:
          description: OK
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/ParkingLotDetails'

components:
  schemas:
    ParkingLotDetails:
     type: object
     description: The details of the parking lots for a mall.
     properties:
       parkingLots: 
        type: array
        description: The list of parking lots available in a shopping mall.
        items: 
          $ref: '#/components/schemas/ParkingLotGroup'
     example:  { 
                "parkingLots":[
                    {
                        "floor":"GROUND_FLOOR",
                        "zone": "A0",
                        "startingSlot":1,
                        "endingSlot": 20
                    },
                    {
                        "floor":"GROUND_FLOOR",
                        "zone": "B0",
                        "startingSlot":1,
                        "endingSlot": 20
                    },
                            {
                        "floor":"FIRST_FLOOR",
                        "zone": "A1",
                        "startingSlot":1,
                        "endingSlot": 15
                    },        {
                        "floor":"FIRST_FLOOR",
                        "zone": "B1",
                        "startingSlot":1,
                        "endingSlot": 25
                    }
                ]
            }
    ParkingLotGroup:
      type: object
      description: The details of a parking lot group.
      properties:
        floor: 
          type: string
          description: The floor in which the parking lot group is situated.
          example: GROUND_FLOOR
          enum:
            - GROUND_FLOOR
            - FIRST_FLOOR
            - SECOND_FLOOR
            - THIRD_FLOOR
            - FOURTH_FLOOR
            - FIFTH_FLOOR
            - SIXTH_FLOOR
            - SEVENTH_FLOOR
            - EIGHTH_FLOOR
            - MINUS_ONE
            - MINUS_TWO
            - DEFAULT
        zone: 
          type: string
          description: The zone name for the parking lot.
          example: A1 
        startingSlot: 
          type: integer
          description: The starting parking slot number in the zone.
          example: 1
        endingSlot:
          type: integer
          description: The ending slot number in the zone.
          example: 20
    ShoppingMallDetails:
      type: object
      description: The details of a shopping mall.
      properties:
        id: 
          type: string
          description: The internal system identifier for the shopping mall
          example: 936hdhjhjkh8881jhdja==
        name: 
          type: string
          description: The name of the shopping mall
          example: HiLite Mall, Kozhikode
        areaCode:
          type: string
          description: The area code associated with the shopping mall.
          example: KZD
          enum: 
            - KZD
        mallImageUrl:
          type: string
          description: The image url for the mall's branding image.
          example: https://s3.ap-south-1.amazonaws.com/proximety.io/profile-pictures-dev/d5b37874-6c6f-43cf-ad3c-f306cb2d360a.png
    LogoutRequest:
      type: object
      description: The logout request.
      properties:
        userId:
          type: string
          description: The internal system identifier for the user trying to log out of the system.
          example: 3hjhf97829132
    LogoutResponse:
      type: object
      description: The logout response.
      properties:
        message: 
          type: string
          description: The logout message.
          example: Logout successful.
    LoginRequest:
      type: object
      description: The request for logging in an admin user.
      properties:
        email:
          type: string
          description: The registered email id for the user.
          example: abc@xyz.com
        password:
          type: string
          description: The passowrd for the user logging into the platform.
          example: 37816dhk
    LoginResponse:
      type: object
      description: The login response.
      properties:
        userId:
          type: string
          description: The internal system identfier for the user logged into the system.
          example: hdjahdihy83871
        mallId:
          type: string
          description: The internal system identifier for the shopping mall to which the admin user has access token.
          example: djajksd89797
        accessToken:
          type: string
          description: The token generated after authentication which needs to be passed in all subsequent calls to the system.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ1bV9hY2Nlc3MiLCJleHAiOjE2NjAyODE5
        accessTokenType: 
          type: string
          description: The type of access token used.
          example: Bearer
        userRole: 
          type: string
          description: The user role for the loggged in user. The logged in user can either be a mall manager or a platform admin.
          example: MANAGER
          enum:
            - MANAGER
            - ADMIN
    GlobalException:
      type: object
      description: An exception thrown by the system.
      properties:
        status:
          type: integer
          description: The status code for the error.
          example: 401
        type:
          type: string
          description: The type name for the error being thrown.
          example: UNAUTHORIZED
        title:
          type: string
          description: The error title.
          example: Token expired.
        detail:
          type: string
          description: The details of the error being thrown.
          example: The access token has expired for the user. Please generate a new token and try again.
        tags:
          type: array
          description: The varios tags associated with the error that provides additional information about the error.
          items: 
            type: string
            example: ACCESS_TOKEN_INVALID
